### ISSUE TITLE
Pumpkin Nudge

### ISSUE THREAD

**Issue by cyanidecupcake** [cyanidecupcake/Autumn-Adventure#1]
How to get pumpkins to move when D or A is pressed and pumpkin is touching player sprite?  (While also maintaining pumpkins as objects you can't walk through)

**Tried:** 
_Issue: Pumpkin keeps moving after key released_
        if key == arcade.key.D:
            for pumpkin in self.pumpkin_hit_list:
                #pumpkin.change_x = PUMPKIN_MOVEMENT_SPEED                       

        if key == arcade.key.A:
                print("PUMPKIN BACK")

**Comment by notklaatu** [comment]
I think setting pumpkin.center_x to self.player_sprite.boundary_right() (or something like that) could be the answer. This would make it so the pumpkin "attaches" to the player sprite and moves along with it until it is "dropped". 

We just need to look at the docs and determine what properties we can get from player sprite, and how to assign it to the pumpkin sprite.

**Comment by cyanidecupcake** [comment]
HUZZAH!! We got code that works and the pumpkin nudge is absolutely adorable.
